//
//  ForecastProtocols.swift
//  weather
//
//  Created Z on 6/11/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ForecastWireframeProtocol: class {
}
//MARK: Presenter -
protocol ForecastPresenterProtocol: class {
    func count()->Int?
    func getForecastInfo(index: Int)->String
    func getTitle()->String
    func loadData()
    func error(text: String)
}

//MARK: Interactor -
protocol ForecastInteractorProtocol: class {
    var presenter: ForecastPresenterProtocol?  { get set }
    func loadAPIRequestForecast(nameTown: String, completion: @escaping (ForecastAPIModel?)->())
    func error(text: String)
}

//MARK: View -
protocol ForecastViewProtocol: class {
    var presenter: ForecastPresenterProtocol?  { get set }
    func update()
    func showError(text: String)
}

protocol ForecastTableViewCellProtocol: class {
    func configCell(text: String)
}
