//
//  ForecastRouter.swift
//  weather
//
//  Created Z on 6/11/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ForecastRouter: ForecastWireframeProtocol {
    weak var viewController: UIViewController?
    
    static func createModule(nameTown: String) -> UIViewController {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let view = storyboard.instantiateViewController(withIdentifier: "ForecaViewController") as! ForecastViewController
        let interactor = ForecastInteractor()
        let router = ForecastRouter()
        let presenter = ForecastPresenter(interface: view as ForecastViewProtocol, interactor: interactor, router: router)
        presenter.nameTown = nameTown
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        return view
    }
}
