//
//  WeatherProtocols.swift
//  weather
//
//  Created Z on 6/11/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol WeatherWireframeProtocol: class {
}
//MARK: Presenter -
protocol WeatherPresenterProtocol: class {
    func count()->Int?
    func getTextWeatherInfo(index: Int)->String
    func getTitle()->String
    func loadData()
}

//MARK: Interactor -
protocol WeatherInteractorProtocol: class {
    var presenter: WeatherPresenterProtocol?  { get set }
    func loadInfo(nameTown: String, completion: @escaping ([WeatherModel]?)->())
}

//MARK: View -
protocol WeatherViewProtocol: class {
    var presenter: WeatherPresenterProtocol?  { get set }
    func update()
}

protocol WeatherTableViewCellProtocol: class {
    func configCell(text: String)
}
