//
//  WeatherViewController.swift
//  weather
//
//  Created Z on 6/11/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WeatherViewController: UIViewController, WeatherViewProtocol {

	var presenter: WeatherPresenterProtocol?
    
    @IBOutlet weak var weatherTableView: UITableView!
    
    @IBOutlet weak var tatleLabel: UILabel!
    
	override func viewDidLoad() {
        super.viewDidLoad()
        tatleLabel.text = presenter?.getTitle()
        presenter?.loadData()
    }

    func update() {
        DispatchQueue.main.async {
            self.weatherTableView.reloadData()
            let sectionIndex = IndexSet(integer: 0)
            self.weatherTableView.reloadSections(sectionIndex, with: .none)
        }
    }
}

extension WeatherViewController:  UITableViewDataSource {
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return presenter?.count() ?? 0
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        let cell = tableView.dequeueReusableCell(withIdentifier:"WeatherTableViewCell", for: indexPath)
        
        if let cell = cell as? WeatherTableViewCellProtocol {
            
            let text = presenter?.getTextWeatherInfo(index: indexPath.row) ?? ""
            
            cell.configCell(text: text)
        }
        
        return cell
    }
}

extension WeatherViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    
    }
}
