//
//  WeatherRouter.swift
//  weather
//
//  Created Z on 6/11/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WeatherRouter: WeatherWireframeProtocol {
    weak var viewController: UIViewController?
    
    static func createModule(nameTown: String) -> UIViewController {
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let view = storyboard.instantiateViewController(withIdentifier: "WeatherViewController") as! WeatherViewController
        let interactor = WeatherInteractor()
        let router = WeatherRouter()
        let presenter = WeatherPresenter(interface: view as WeatherViewProtocol, interactor: interactor, router: router)
        presenter.nameTown = nameTown
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        return view
    }
}
