//
//  WeatherInteractor.swift
//  weather
//
//  Created Z on 6/11/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WeatherInteractor: WeatherInteractorProtocol {
    weak var presenter: WeatherPresenterProtocol?
    
    func loadInfo(nameTown: String, completion: @escaping ([WeatherModel]?)->()) {
        NetworkServiceAPI.shared.loadAPIRequestWeather(nameTown: nameTown) { [weak self] (result: WeatherAPIModel?) in
        guard let list = result?.list else { return }
        let count = list.count
        var weatherModel = [WeatherModel]()
        var date: String = ""
        var tempr: String = ""
        var rain: String = ""
        var main: String = ""
            
        for i in 0..<count {
                date = list[i].dtTxt ?? ""
                if let m = list[i].weather?[0].main?.description {
                    main = m
                }
                if let r = list[i].rain?.the3H {
                    rain = String(describing:  r)
                }
                if let t = list[i].main?.temp {
                    tempr = String(t)
                }
                let text = date + ":\n" +  "tempr - " + tempr + ",\nmain - " + main + ",\nrain - " + rain
                weatherModel.append(WeatherModel(weatherForecast: text))
            }
            completion(weatherModel)
        }
    }
}
