//
//  TownRouter.swift
//  weather
//
//  Created Z on 6/11/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TownRouter: TownWireframeProtocol {
    weak var viewController: TownViewController? // UIViewController?
    
    static func createModule(view: TownViewController) {
        // Change to get view from storyboard if not using progammatic UI
        let view = view
        let interactorDB = TownInteractorDB()
        let interactorAPI = TownInteractorAPI()
        let router = TownRouter()
        let presenter = TownPresenter(interface: view, interactorAPI: interactorAPI, interactorDB: interactorDB, router: router)
        
        view.presenter = presenter
        interactorAPI.presenter = presenter
        interactorDB.presenter = presenter
        router.viewController = view
    }
    
    func showForecastView(nameTown: String) {
        let view = ForecastRouter.createModule(nameTown: nameTown)
        self.viewController?.navigationController?.pushViewController(view, animated: true)
    }
}
