//
//  TownProtocols.swift
//  weather
//
//  Created Z on 6/11/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol TownWireframeProtocol: class {
    func showWeatherView()
}
//MARK: Presenter -
protocol TownPresenterProtocol: class {
    
    var townModel: [TownModel]? {get set}
    
    func count()->Int?
    func actionCellButton(index: Int?)
    func getTextTownInfo(index: Int)->String
    func getTypeTownInfo(index: Int)->Bool
    func showWeatherView()
    
}

//MARK: Interactor -
protocol TownInteractorProtocol: class {

  var presenter: TownPresenterProtocol?  { get set }
}

//MARK: View -
protocol TownViewProtocol: class {

  var presenter: TownPresenterProtocol?  { get set }
}

protocol TownTableViewCellDelegate: class {
    func getIndex(index: Int?)  //ShoppingCart
}


protocol TownTableViewCellProtocol: class {
    
    var presenter: TownTablePresenterCellProtocol?  { get set }
    func configCell(text: String, type: Bool, index: Int, delegate: TownTableViewCellDelegate)
}

protocol TownTablePresenterCellProtocol: class {
    var index: Int? {get set}
}

