//
//  TownPresenter.swift
//  weather
//
//  Created Z on 6/11/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TownPresenter: TownPresenterProtocol {

    weak private var view: TownViewProtocol?
    var interactor: TownInteractorProtocol?
    private let router: TownWireframeProtocol

    init(interface: TownViewProtocol, interactor: TownInteractorProtocol?, router: TownWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

    func actionCellButton(index: Int?) {
        print(index)
    }
}
