//
//  TownProtocols.swift
//  weather
//
//  Created Z on 6/11/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol TownWireframeProtocol: class {

}
//MARK: Presenter -
protocol TownPresenterProtocol: class {

}

//MARK: Interactor -
protocol TownInteractorProtocol: class {

  var presenter: TownPresenterProtocol?  { get set }
}

//MARK: View -
protocol TownViewProtocol: class {

  var presenter: TownPresenterProtocol?  { get set }
}
