//
//  WeatherTownInteractor.swift
//  weather
//
//  Created Z on 7/14/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WeatherTownInteractor: WeatherTownInteractorProtocol {

    weak var presenter: WeatherTownPresenterProtocol?
}
