//
//  WeatherTownProtocols.swift
//  weather
//
//  Created Z on 7/14/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol WeatherTownWireframeProtocol: class {
    func showForecastView(nameTown: String)
}
//MARK: Presenter -
protocol WeatherTownPresenterProtocol: class {
    func count()->Int
    func actionChangeCell(index: Int?)
    func getTextTownInfo(index: Int)->(String, String, String)
    func getTypeTownInfo(index: Int)->Bool
    func showForecastView(indexCell: Int)
    func choiceTown(townName: String?)
    func addTown(townName: String?)
    func updata(towns: [TownModel]?)
    func error(text: String)
}

//MARK: Interactor -
protocol WeatherTownInteractorProtocol: class {

  var presenter: WeatherTownPresenterProtocol?  { get set }
}

//MARK: View -
protocol WeatherTownViewProtocol: class {

  var presenter: WeatherTownPresenterProtocol?  { get set }
    
    func update()
    func showError(text: String)
}

protocol WeatherTownInteractorDBProtocol: class {
    var presenter: WeatherTownPresenterProtocol?  { get set }
    
    func addItem(item: TownItemDB, completion: @escaping (String?)->())
    func getItems(completion: @escaping ([TownItemDB]?)->())
    func error(text: String)
}
protocol WeatherTownInteractorAPIProtocol: class {
    var presenter: WeatherTownPresenterProtocol?  { get set }
    
    func loadAPIRequestTown(nameTown: String, completion: @escaping (TownAPIModel?)->())
    func error(text: String)
}

protocol WeatherTownTableViewCellDelegate: class {
    func getIndex(index: Int?)  //ShoppingCart
}

