//
//  WeatherTownRouter.swift
//  weather
//
//  Created Z on 7/14/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class WeatherTownRouter: WeatherTownWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = WeatherTownViewController(nibName: nil, bundle: nil)
        let interactor = WeatherTownInteractor()
        let interactorDB = WeatherTownInteractorDB()
        let interactorAPI = WeatherTownInteractorAPI()
        
        let router = WeatherTownRouter()
        //let presenter = WeatherTownPresenter(interface: view, interactor: interactor, router: router)
        let presenter = WeatherTownPresenter(interface: view, interactorAPI: interactorAPI, interactorDB: interactorDB, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        interactorAPI.presenter = presenter
        interactorDB.presenter = presenter
        router.viewController = view

        return view
    }
    
    func showForecastView(nameTown: String) {
        let view = ForecastRouter.createModule(nameTown: nameTown)
        self.viewController?.navigationController?.pushViewController(view, animated: true)
    }
}

