//
//  ForecastWeatherProtocols.swift
//  weather
//
//  Created Z on 7/15/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ForecastWeatherWireframeProtocol: class {
   
}
//MARK: Presenter -
protocol ForecastWeatherPresenterProtocol: class {
    func count()->Int?
    func getForecastInfo(index: Int)->String
    func getTitle()->String
    func loadData()
    func error(text: String)
}

//MARK: Interactor -
protocol ForecastWeatherInteractorProtocol: class {

    var presenter: ForecastWeatherPresenterProtocol?  { get set }
    func loadAPIRequestForecast(nameTown: String, completion: @escaping (ForecastAPIModel?)->())
    func error(text: String)
}

//MARK: View -
protocol ForecastWeatherViewProtocol: class {

    var presenter: ForecastWeatherPresenterProtocol?  { get set }
    func update()
    func showError(text: String)
}
