//
//  ForecastWeatherRouter.swift
//  weather
//
//  Created Z on 7/15/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ForecastWeatherRouter: ForecastWeatherWireframeProtocol {
    
    weak var viewController: UIViewController?
    
    static func createModule(nameTown: String) -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ForecastWeatherViewController(nibName: nil, bundle: nil)
        let interactor = ForecastWeatherInteractor()
        let router = ForecastWeatherRouter()
        let presenter = ForecastWeatherPresenter(interface: view, interactor: interactor, router: router)
        presenter.nameTown = nameTown
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}
