//
//  ForecastWeatherViewController.swift
//  weather
//
//  Created Z on 7/15/19.
//  Copyright © 2019 Zyma. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ForecastWeatherViewController: UIViewController, ForecastWeatherViewProtocol {

	var presenter: ForecastWeatherPresenterProtocol?
    let townCell = "ForecastTableCell"
    @IBOutlet weak var nameTownLabel: UILabel!
    @IBOutlet weak var forecastTableView: UITableView!
    
    
    
	override func viewDidLoad() {
        super.viewDidLoad()
        
        forecastTableView.delegate = self
        forecastTableView.dataSource = self
        forecastTableView.register(UINib(nibName: townCell, bundle: nil), forCellReuseIdentifier: townCell)
        forecastTableView.rowHeight = UITableView.automaticDimension
        
        nameTownLabel.text = presenter?.getTitle()
        presenter?.loadData()
    }
    
    func update() {
        DispatchQueue.main.async {
            self.forecastTableView.reloadData()
            let sectionIndex = IndexSet(integer: 0)
            self.forecastTableView.reloadSections(sectionIndex, with: .none)
        }
    }
    
    func showMessage(title: String, text: String, action repeatHandler: @escaping ()->()) {
        let alertAction = UIAlertAction(title: "OK", style: .default) { (action) in
            repeatHandler()
        }
        let controller = UIAlertController(title: title, message: text, preferredStyle: .alert)
        controller.addAction(alertAction)
        
        DispatchQueue.main.async {
            self.present(controller, animated: true, completion: nil)
        }
    }
    
    func showError(text: String) {
        DispatchQueue.main.async {
            // self.indicator.stopAnimating()
            self.showMessage(title: "ERROR", text: text) { () in
                
            }
        }
    }
}

extension ForecastWeatherViewController:  UITableViewDataSource {
    func numberOfSections(in tableView: UITableView) -> Int {
        return 1
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return presenter?.count() ?? 0
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        
        let cell = tableView.dequeueReusableCell(withIdentifier: townCell, for: indexPath)
        
        if let cell = cell as? ForecastTableCell {
              let text = presenter?.getForecastInfo(index: indexPath.row) ?? ""
              cell.forecastInfoLabel.text = text
        }
        return cell
    }
}

extension ForecastWeatherViewController: UITableViewDelegate {
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
    }
}

